- name: Install Prometheus and Grafana
  hosts: monitoring
  become: true

  tasks:
    - name: Install prerequisites
      apt:
        name:
          - wget
          - curl
          - gnupg2
          - apt-transport-https
          - software-properties-common
        update_cache: yes

    - name: Add Grafana APT key
      apt_key:
        url: https://packages.grafana.com/gpg.key
        state: present

    - name: Add Grafana repo
      apt_repository:
        repo: "deb https://packages.grafana.com/oss/deb stable main"
        state: present

    - name: Install Grafana
      apt:
        name: grafana
        update_cache: yes
        state: present

    - name: Enable and start Grafana
      systemd:
        name: grafana-server
        enabled: true
        state: started

    - name: Download Prometheus tarball
      get_url:
        url: https://github.com/prometheus/prometheus/releases/download/v2.45.0/prometheus-2.45.0.linux-amd64.tar.gz
        dest: /tmp/prometheus.tar.gz

    - name: Extract Prometheus
      unarchive:
        src: /tmp/prometheus.tar.gz
        dest: /opt/
        remote_src: yes

    - name: Move Prometheus binaries
      copy:
        remote_src: yes
        src: /opt/prometheus-2.45.0.linux-amd64/
        dest: /opt/prometheus/
    
    - name: Create Prometheus service file
      copy:
        dest: /etc/systemd/system/prometheus.service
        content: |
          [Unit]
          Description=Prometheus
          Wants=network-online.target
          After=network-online.target

          [Service]
          User=root
          ExecStart=/opt/prometheus/prometheus --config.file=/opt/prometheus/prometheus.yml

          [Install]
          WantedBy=default.target

    - name: Reload systemd and start Prometheus
      systemd:
        daemon_reload: yes
        name: prometheus
        enabled: yes
        state: started
